name: Tests
on: [push]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable

      - name: ESLint
        run: yarn lint

      - name: Prettier
        run: yarn pretty
      
      - name: Build
        run: yarn build
