name: tests
on: [push, workflow_dispatch]
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install bun :3
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: install node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'bun'
          cache-dependency-path: bun.lockb

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: lint >:D
        run: bun lint

      - name: pretty :o
        run: pnpm pretty
      
      - name: build !!
        run: pnpm build
